CREATE DATABASE ecommerce;

USE ecommerce;

CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT
);

CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Insert dummy data into categories
INSERT INTO categories (name, description) VALUES
('Electronics', 'Devices and gadgets'),
('Clothing', 'Apparel and accessories'),
('Books', 'Printed and digital books'),
('Home & Kitchen', 'Home appliances and kitchen tools'),
('Sports & Outdoors', 'Sports equipment and outdoor gear'),
('Toys & Games', 'Toys and games for all ages'),
('Beauty & Personal Care', 'Beauty and personal care products'),
('Health & Wellness', 'Health and wellness products'),
('Automotive', 'Automotive parts and accessories'),
('Furniture', 'Home and office furniture');

-- Insert dummy data into products
INSERT INTO products (name, description, price, category_id) VALUES
('Smartphone', 'Latest model smartphone', 999.99, 1),
('Laptop', 'High-performance laptop', 1299.99, 1),
('T-shirt', 'Cotton t-shirt', 19.99, 2),
('Novel', 'Bestselling novel', 14.99, 3),
('Blender', 'High-speed blender', 89.99, 4),
('Yoga Mat', 'Eco-friendly yoga mat', 29.99, 5),
('Board Game', 'Family board game', 39.99, 6),
('Lipstick', 'Long-lasting lipstick', 9.99, 7),
('Vitamin C', 'Immune support vitamins', 19.99, 8),
('Car Charger', 'Fast car charger', 24.99, 9),
('Desk Chair', 'Ergonomic desk chair', 199.99, 10),
('Tablet', 'Lightweight tablet', 499.99, 1),
('Jeans', 'Slim-fit jeans', 49.99, 2),
('Cookbook', 'Healthy recipes cookbook', 24.99, 3),
('Air Fryer', 'Digital air fryer', 119.99, 4),
('Tent', '4-person camping tent', 149.99, 5),
('LEGO Set', 'Creative building set', 59.99, 6),
('Moisturizer', 'Hydrating face moisturizer', 14.99, 7),
('Protein Powder', 'Whey protein powder', 29.99, 8),
('Car Wax', 'Premium car wax', 19.99, 9),
('Sofa', '3-seater leather sofa', 899.99, 10),
('Smartwatch', 'Fitness tracking smartwatch', 199.99, 1),
('Hoodie', 'Warm hoodie', 39.99, 2),
('Mystery Novel', 'Thrilling mystery novel', 12.99, 3),
('Coffee Maker', 'Programmable coffee maker', 79.99, 4),
('Running Shoes', 'Lightweight running shoes', 89.99, 5),
('Puzzle', '1000-piece puzzle', 19.99, 6),
('Shampoo', 'Volumizing shampoo', 8.99, 7),
('Fish Oil', 'Omega-3 fish oil', 24.99, 8),
('Car Seat Cover', 'Luxury car seat cover', 49.99, 9),
('Dining Table', '6-seater dining table', 499.99, 10),
('Headphones', 'Noise-cancelling headphones', 149.99, 1),
('Jacket', 'Waterproof jacket', 79.99, 2),
('Science Fiction Book', 'Award-winning sci-fi book', 16.99, 3),
('Microwave', 'Compact microwave oven', 99.99, 4),
('Bicycle', 'Mountain bike', 299.99, 5),
('Action Figure', 'Collectible action figure', 29.99, 6),
('Sunscreen', 'SPF 50 sunscreen', 12.99, 7),
('Multivitamin', 'Daily multivitamin', 19.99, 8),
('Car Floor Mats', 'All-weather car floor mats', 39.99, 9),
('Bookshelf', '5-tier bookshelf', 149.99, 10),
('Earbuds', 'Wireless earbuds', 79.99, 1),
('Sweater', 'Knit sweater', 59.99, 2),
('Biography', 'Inspirational biography', 18.99, 3),
('Toaster', '2-slice toaster', 39.99, 4),
('Treadmill', 'Folding treadmill', 499.99, 5),
('Dollhouse', 'Wooden dollhouse', 89.99, 6),
('Face Mask', 'Hydrating face mask', 6.99, 7),
('Probiotics', 'Digestive health probiotics', 29.99, 8),
('Car Vacuum', 'Portable car vacuum', 49.99, 9),
('Recliner', 'Comfortable recliner chair', 299.99, 10),
('Monitor', '27-inch 4K monitor', 299.99, 1),
('Shorts', 'Casual shorts', 29.99, 2),
('History Book', 'World history book', 22.99, 3),
('Rice Cooker', 'Automatic rice cooker', 59.99, 4),
('Dumbbells', 'Adjustable dumbbells', 79.99, 5),
('RC Car', 'Remote control car', 49.99, 6),
('Body Lotion', 'Nourishing body lotion', 9.99, 7),
('Collagen', 'Beauty collagen supplement', 34.99, 8),
('Car Air Freshener', 'Scented car air freshener', 4.99, 9),
('Bed Frame', 'Queen-size bed frame', 399.99, 10),
('Printer', 'Wireless printer', 129.99, 1),
('Dress', 'Elegant evening dress', 89.99, 2),
('Poetry Book', 'Collection of modern poetry', 14.99, 3),
('Blender Bottle', 'Shaker bottle for protein', 9.99, 4),
('Yoga Block', 'Foam yoga block', 7.99, 5),
('Building Blocks', 'Educational building blocks', 29.99, 6),
('Face Cleanser', 'Gentle face cleanser', 11.99, 7),
('Turmeric', 'Organic turmeric supplement', 19.99, 8),
('Car Phone Mount', 'Dashboard phone mount', 14.99, 9),
('Nightstand', 'Bedside nightstand', 79.99, 10),
('External Hard Drive', '1TB external hard drive', 59.99, 1),
('Socks', 'Pack of 6 cotton socks', 12.99, 2),
('Cookbook', 'Vegan recipes cookbook', 19.99, 3),
('Electric Kettle', 'Stainless steel kettle', 34.99, 4),
('Jump Rope', 'Adjustable jump rope', 9.99, 5),
('Plush Toy', 'Soft plush toy', 14.99, 6),
('Hand Cream', 'Moisturizing hand cream', 7.99, 7),
('Melatonin', 'Sleep support melatonin', 12.99, 8),
('Car Jump Starter', 'Portable car jump starter', 99.99, 9),
('Coffee Table', 'Modern coffee table', 149.99, 10),
('Graphics Card', 'High-end graphics card', 499.99, 1),
('Scarf', 'Woolen scarf', 24.99, 2),
('Fantasy Novel', 'Epic fantasy novel', 17.99, 3),
('Food Processor', 'Multi-functional food processor', 129.99, 4),
('Resistance Bands', 'Set of 5 resistance bands', 19.99, 5),
('Card Game', 'Strategy card game', 24.99, 6),
('Lip Balm', 'Hydrating lip balm', 3.99, 7),
('Ashwagandha', 'Stress relief supplement', 29.99, 8),
('Car Seat Cushion', 'Gel car seat cushion', 29.99, 9),
('TV Stand', 'Universal TV stand', 99.99, 10),
('Keyboard', 'Mechanical gaming keyboard', 89.99, 1),
('Gloves', 'Winter gloves', 19.99, 2),
('Self-Help Book', 'Motivational self-help book', 13.99, 3),
('Slow Cooker', 'Programmable slow cooker', 69.99, 4),
('Hiking Boots', 'Durable hiking boots', 109.99, 5),
('Stuffed Animal', 'Cute stuffed animal', 12.99, 6),
('Eye Cream', 'Anti-aging eye cream', 24.99, 7),
('Magnesium', 'Muscle relaxation supplement', 19.99, 8),
('Car Organizer', 'Backseat car organizer', 19.99, 9),
('Desk Lamp', 'Adjustable desk lamp', 39.99, 10);